
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "./src", "/home/vagrant/src", create: true
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "forwarded_port", guest: 80, host: 8000

  #config.push.define "ftp" do |push|
  #  push.host = "ftp.company.com"
  #  push.username = "username"
  #  push.password = "mypassword"
  #end

end
